server:
  port: 9630

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/


spring:


  application:
    name: MAIN

  r2dbc:
    url: r2dbc:postgresql://localhost:5000/postgres
    username: root
    password: toor

  output:
    ansi:
      enabled: ALWAYS


secret: ?????????_$2a$13$.C.OIsL4OWA6HB1NENTudeIz28Syv7VSR7TDwTo7yfqFw2vZD/JdC
validTime: 120_000
host: "localhost:9630"