version: '3'

services:
  redis:
    restart: always
    image: "redis:latest"
    container_name: redis
    ports:
    - "6379:6379"

  mongodb:
    restart: always
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"

  zookeeper-1:
    restart: always
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  zookeeper-2:
    restart: always
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2182:2181

  kafka:
    restart: always
    image: 'bitnami/kafka:latest'
    ports:
      - '8083:8083'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:8083
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:8083
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1:2181 , zookeeper-2:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-1
      - zookeeper-2
  kafka2:
    restart: always
    image: 'bitnami/kafka:latest'
    ports:
      - '8084:8083'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:8083
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:8083
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1:2181 , zookeeper-2:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-1
      - zookeeper-2