server:
  port:
    9380

spring:
  application:
    name: EMAIL

  mail:
    host: smtp.gmail.com
    port: 587
    username: rsumakov20@gmail.com
    password: "**********"
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers:
      - localhost:8084
      - localhost:8083
    consumer:
      auto-offset-reset: earliest
      group-id: qr_auth
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer