package com.valet.qr_registration_server.model.changeAction;

public enum ActionType {
    CHANGE_PASSWORD, CHANGE_USERNAME, CHANGE_JOB_TITLE,
    CHANGE_ORGANIZATION, REGISTRATION, CHANGE_ROLE,
    CREATE_ORGANIZATION, ADD_IN_COMMAND, ADD_IN_COMMAND_AND_MAKE_ADMIN
}
