server:
  port: 9999

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
spring:
  output:
    ansi:
      enabled: ALWAYS
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5000/postgres
    username: root
    password: toor