server:
  port: 9730

spring:

  application:
    name: "DBSERVER"

  r2dbc:
    url: r2dbc:postgresql://localhost:5000/postgres
    username: root
    password: toor

  output:
    ansi:
      enabled: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/