package com.valet.qrdbserver.model.action;

public enum ActionType {
    CHANGE_PASSWORD,
    CHANGE_USERNAME,
    CHANGE_JOB_TITLE,
    CHANGE_ORGANIZATION,
    REGISTRATION,
    CHANGE_ROLE,
    CREATE_ORGANIZATION,
    ADD_RECORD,
    DELETE_USER,
    HELLO_EMAIL,
    CREATE_TEAM,
    ADD_IN_TEAM,
    DELETE_TEAM,
    CHANGE_OWN_TEAM,
    CHANGE_OWN_ORGANIZATION,
    DELETE_ORGANIZATION
}
